# Generated by Django 3.1.7 on 2021-03-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('A', models.CharField(max_length=1000)),
                ('B', models.CharField(max_length=1000)),
                ('C', models.CharField(max_length=1000)),
                ('D', models.CharField(max_length=1000)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
            ],
        ),
    ]
