# Generated by Django 3.1.7 on 2021-03-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='A',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='B',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='C',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='D',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=models.TextField(max_length=1000),
        ),
    ]
